// Auto-generated module registry. Regenerated by the builder.
import m0 from "./modules/core/auth/meta.mjs";
import m1 from "./modules/core/users/meta.mjs";
import m2 from "./modules/acc/cari/meta.mjs";
import m3 from "./modules/acc/fatura/meta.mjs";
import m4 from "./modules/acc/islem/meta.mjs";
import m5 from "./modules/acc/kasa/meta.mjs";

export const MODULES = [m0, m1, m2, m3, m4, m5];
export const TABLES = MODULES.flatMap((m) => m.tables);
export const PAGES = MODULES.flatMap((m) => m.pages);
export const MENU = MODULES.flatMap((m) => m.menu);
export const PERMISSIONS = MODULES.flatMap((m) => m.permissions);
export const WIDGETS = MODULES.flatMap((m) => m.widgets ?? []);
